version: 2

models:
  # We specify the table that we want to test
  - name:  dim_listings_cleansed
    columns:
      # We specify what tests we want to run on the column
      # In a regular SQL DB, these validations would exist on the model itself
      # However, in certain data lakes, we can't enforce these validations, ex Snowflake
      - name: listing_id
        tests:
            - unique
            - not_null

      - name: host_id
        tests:
            - not_null
            # Checking that there is a valid relationship to another table
            - relationships:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        tests:
          # Checking that the values are within a list of accepted values
          - accepted_values:
              values: [
                'Entire home/apt',
                'Private room',
                'Shared room',
                'Hotel room'
              ]

      - name: minimum_nights
        tests:
          - positive_integer_value